server:
  port: 6060
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: eureka-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.16.27:3306/openbeauty?characterEncoding=utf8&roundRobinLoadBalance=true&useUnicode=true&useSSL=false
    username: root
    password: root
  profiles:
    active: mysql
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        #open-in-view: false  #默认开启，开启可以在控制台看到数据库查询情况
  http:
    encoding:
      charset: utf-8
      enabled: true

#服务发现配置
eureka:
  #指定主机名称
  instance:
    hostname: localhost
  client:
    #是否将自己注册到注册中心，本身就是注册中心，不需要
    register-with-eureka: false
    #是否从Eureka中获取注册信息
    fetch-registry: false
    #Eureka客户端和服务端进行交互地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
