server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/openbeauty?characterEncoding=utf8&roundRobinLoadBalance=true&useUnicode=true&useSSL=false
    username: root
    password: root
  profiles:
    active: mysql
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        #open-in-view: false  #默认开启，开启可以在控制台看到数据库查询情况
  http:
    encoding:
      charset: utf-8
      enabled: true

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    #配置html页面静态资源路径,以后用Nginx代理获取
    prefix: classpath:/static/
  resources:
    static-locations: classpath:/static/
logging:
  path: /logs/parent/log
  file: spring.log
