server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8
logging:
  path: ./home/parent/logs
  file: spring.log
spring:
  application:
    name: public-start #指定当前服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.16.27:3306/openbeauty?characterEncoding=utf8&roundRobinLoadBalance=true&useUnicode=true&useSSL=false
    username: root
    password: root
  profiles:
    active: mysql
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        #open-in-view: false  #默认开启，开启可以在控制台看到数据库查询情况
  http:
    encoding:
      charset: utf-8
      enabled: true

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    #配置html页面静态资源路径,以后用Nginx代理获取
    prefix: classpath:/static/

    servlet:
      content-type: text/html

  mvc:
    static-path-pattern: /**
  #配置js、css资源路径，以后用Nginx代理获取
  resources:
    static-locations: classpath:/static/
  #配置redis
  redis:
    host: http://192.168.16.29:6379

#服务发现客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6060/eureka
